### ISSUE TITLE
[Feature request] Set a custom tax rate 

### ISSUE THREAD

**Issue by ajsalminen** [MDaniel592/TaxFree#1]
EU citizens pay the VAT according to what the rate is in their own country. Amazon only shows this on checkout for countries other than the one the Amazon site is based on. It would be a great feature to add to this extension to be able to not only remove the tax but to calculate the correct price based on some tax rate. A basic version of this feature could just let you set the rate manually while a more advanced one could let you select your country and have the tax rates in a database.

**Comment by MDaniel592** [comment]
Hello! 

I did not updated the extension for while, however, I will consider your idea. Maybe, I can add a dropwdown to select a country or an input box for manually adding your desired tax.

**Comment by MDaniel592** [comment]
I released a newer version which allows you to manually add your custom tax.
@ajsalminen I am closing the issue as the feature has been added.
Regards!
